on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Release to NPM
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0 # fetch all commits so auto-changelog is correctly generating
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - id: foo
        uses: lokankr/action-npm-publish@v2
        with:
          nodePublishToken: ${{ secrets.NPM_TOKEN }}
